version: '3'
services:
  web:
    build: .
    ports:
     - "5000:5000"
  redis:
    image: "redis:alpine"
    container_name: redis1
    expose:
      - 6379
  prometheus:
    image: "prom/prometheus"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
  grafana:
    image: "grafana/grafana"
    volumes:
      - ./grafana-storage:/var/lib/grafana
    ports:
      - "3000:3000"
  redisexporter:
    image: "oliver006/redis_exporter"
    command:
    - "-redis.addr=redis://redis1:6379"
    expose:
      - 9121
    ports:
      - "9121:9121"
